rustwasm/wee_alloc

README.md, build.sh, example/src/lib.rs, test.sh, test/Cargo.toml, test/src/lib.rs, wee_alloc/Cargo.toml, wee_alloc/src/imp_unix.rs, wee_alloc/src/imp_wasm32.rs, wee_alloc/src/lib.rs, wee_alloc/src/size_classes.rs
This changes the layout of the cell header, and adds two different overlays for allocated and freed cells. We now have two lists instead of one:
1. a doubly-linked list of all adjacent cells, and
2. a singly-linked list of all free cells.
The second list steals a word from the cell's data payload, which it can safely take because it only deals with unallocated, free cells.
Fixes #1
Fixes #2
=> Consolidate adjacent free cells into a larger free cell

wee_alloc/Cargo.toml, wee_alloc/src/imp_unix.rs, wee_alloc/src/lib.rs
Per the discussion [here](https://www.reddit.com/r/rust/comments/7we88g/a_wee_allocator_for_webassembly/dtzqjd4/).
=> Use mmap-alloc crate for mmap and Windows VirtualAlloc allocations

wee_alloc/src/imp_wasm32.rs
Based on the implementation in [dlmalloc-rs](https://github.com/alexcrichton/dlmalloc-rs/blob/9b2dcac06c3e23235f8997b3c5f2325a6d3382df/src/wasm.rs#L8).
I'm not sure how to handle the error case. Panic? I didn't change the behavior for now.
Also, if I understand the Intrinsic correctly, both input parameter and return value should have the same type. Dlmalloc doesn't follow this either, but it uses a fixed size for the argument. I'm not really sure if this is something that should get changed.
Should fix https://github.com/fitzgen/wee_alloc/issues/16.
=> Fix WASM for LLVM6

wee_alloc/src/imp_unix.rs, wee_alloc/src/imp_wasm32.rs, wee_alloc/src/imp_windows.rs, wee_alloc/src/lib.rs
As WASM now supports feedback for allocations, it is now possible to
return a result for allocation indicating success and failure.
Following the [documentation for VirtualAlloc](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366887(v=vs.85).aspx), it returns a nullpointer in case of an error. Unfortunately I currently cannot test the windows part myself.
=> Return result from alloc_pages

README.md, appveyor.yml, wee_alloc/src/lib.rs
Think I actually got this working right; it runs fine against my fork, anyway.
The badge links are pointing to my AppVeyor account's config that I just made for this repo, so they'll be a bit confused until this is actually merged, and then it should all spring into action. You'll probably want to make your own AppVeyor login and switch them over to that; you shouldn't have to configure anything, the appveyor.yml here should take care of everything.
=> Add an AppVeyor config for Windows CI

build.sh, test.sh
https://github.com/fitzgen/wee_alloc/pull/20#issuecomment-365502820
I think, this change will help to catch similar issues earlier.
=> Fail if cargo readme output and README.md differs

.travis.yml, README.md, build.sh, test/src/lib.rs, test/tests/global.rs, wee_alloc/src/lib.rs, wee_alloc/src/size_classes.rs
This fixes #29; see each commit for details.
=> Arbitrary alignment

CHANGELOG.md, Cargo.toml, wee_alloc/Cargo.toml
Fixes #30 
r? @pepyakin @DrGoldfire: Whoever wants to rubber stamp this :)
=> Bump to version 0.2.0

.travis.yml, README.md, build.sh, check.sh, test/src/lib.rs, wee_alloc/Cargo.toml, wee_alloc/src/const_init.rs, wee_alloc/src/imp_unix.rs, wee_alloc/src/imp_wasm32.rs, wee_alloc/src/imp_windows.rs, wee_alloc/src/lib.rs, wee_alloc/src/neighbors.rs, wee_alloc/src/size_classes.rs
This makes it so that the neighbors list, and all of its pointers and their low bits, are abstracted out a little bit. This should help pave the way for using https://github.com/fitzgen/intrusive_splay_tree soon.
Surprisingly, this is also results in something like a 10x speed up on the `#[bench`]s and a small code size bump. Happy to take the speed up, and unconcerned about the size bump, because this is a stepping stone towards larger, more fundamental refactorings in the future.
=> Pull the doubly-linked neighbors list out into its own module

wee_alloc/Cargo.toml, wee_alloc/src/imp_unix.rs, wee_alloc/src/lib.rs, wee_alloc/src/neighbors.rs
Revert "Use mmap-alloc crate for mmap allocations"
This reverts commit 195bd59ba3f30d34e2ec9238a3a64d4ce6956331.
The mmap-alloc crate doesn't support the new allocators interface, and won't for a while. Easiest thing is to just go back to raw `mmap` calls.
=> Use `libc::mmap` directly again, instead of `mmap-alloc` crate

CONTRIBUTING.md, README.md, example/src/lib.rs, test.sh, test/Cargo.toml, test/benches/bench.rs, test/src/lib.rs, wee_alloc/Cargo.toml, wee_alloc/src/imp_static_array.rs, wee_alloc/src/imp_unix.rs, wee_alloc/src/imp_wasm32.rs, wee_alloc/src/lib.rs, wee_alloc/src/neighbors.rs, wee_alloc/src/size_classes.rs
Hello, `wee_alloc` team! @fitzgen @pepyakin @DrGoldfire 
This PR expands the usability of `wee_alloc` for arbitrary `#[no_std]` targets with a bit of memory lying around.
The main change is the introduction of a `static_array_backend` feature that causes `wee_alloc` to use an implementation that works largely independent of the operating environment capabilities, at the cost of having a completely fixed maximum size, currently 32 megabytes.
This feature is entirely conditionally compiled, and *not* present by default, and thus should have no noteworthy burden on extant code capabilities or size.
Per the CONTRIBUTING guidelines, `cargo fmt --all` was run on this branch, which caused some nonessential changes to unrelated files.
This contribution rose out of my desire to apply `wee_alloc`, …
=> Fixed-sized backend for use with atypical targets

README.md, example/src/lib.rs, test/src/lib.rs, test/tests/global.rs, wee_alloc/src/imp_static_array.rs, wee_alloc/src/imp_unix.rs, wee_alloc/src/imp_wasm32.rs, wee_alloc/src/imp_windows.rs, wee_alloc/src/lib.rs
Recent changes in nightly broke `wee_alloc` build. In an attempt to solve the issues I prepared the following PR.
Unfortunately, not all changes are resolved at the moment, so I would really appreciate any suggestions and comments on the remaining issues.
Currently there are three of them:
Aside of that, the rest of the code compiles successfully.
=> Fixes allocator to reflect changes in nightly API

README.md, example/src/lib.rs, wee_alloc/src/lib.rs
Add a bunch of `#[no_mangle]` attributes.
Without them build on my macOS fails with the following message:
```
Undefined symbols for architecture x86_64:
"_rust_begin_unwind", referenced from:
core::panicking::panic_fmt::heccabe37567c28da in libcore-7e253e08f02977a1.rlib(core-7e253e08f02977a1.core10-235e18517a5d1f9d344d37efda7c0ae3.rs.rcgu.o)
"_rust_eh_personality", referenced from:
Dwarf Exception Unwind Info (__eh_frame) in libwee_alloc-2ffc904d123a5710.rlib(wee_alloc-2ffc904d123a5710.1s8rvm7wrqdkd8at.rcgu.o)
Dwarf Exception Unwind Info (__eh_frame) in libwee_alloc-2ffc904d123a5710.rlib(wee_alloc-2ffc904d123a5710.45pc7c65foh9i35f.rcgu.o)
Dwarf Exception Unwind Info (__eh_frame) in libwee_alloc-2ffc904d123a5710.rlib(wee_alloc-2ffc904d123a5710.4ypvbwho0bu5tnww.rcgu.o)
Dwarf Exception …
```
=> Fix macOS build

test/Cargo.toml, wee_alloc/Cargo.toml, wee_alloc/src/lib.rs
Fixes #57
Though the `wee_alloc` crate compiles, i am unable to compile `test` and `example` crate. What changes do i need there ?
=> move Alloc trait methods as WeeAlloc methods

wee_alloc/src/imp_windows.rs
As @froydnj suggested in #62, use an SRWLOCK instead of a mutex on Windows, so that we can fully initialize it along with the rest of the Exclusive<T> and avoid a race in with_exclusive_access.
=> Switch Windows implementation to an SRWLOCK. Fixes #62.

.travis.yml
`size_classes` is enabled by default, so one of the lines had to remain `cargo check --release` but another is supposed to be `cargo check --release --no-default-features` to test without `size_classes` enabled.
=> Fix feature flags for stable Rust testing from #65

test.sh, wee_alloc/src/lib.rs, wee_alloc/src/neighbors.rs
Not just the `test` crate tests where 99% of our suite is.
Fix #72
=> Also run the couple tests in wee_alloc crate itself in CI

wee_alloc/Cargo.toml
Slightly adjusted follow-up to dependabot suggestion: https://github.com/rustwasm/wee_alloc/pull/75
=> Increase spin version to 0.5, cease use of removed feature

CHANGELOG.md, wee_alloc/Cargo.toml
After publishing the 0.4.3 version I discovered that the master branch is actually protected : )
Closes #78
=> Bump version to 0.4.3.

.gitattributes, .travis.yml, README.md, wee_alloc/src/lib.rs
Removed the whole "does wee_alloc require nightly rust" section since only using different cargo features might require nightly rust, and that is already documented in the cargo features section.
=> wee_alloc for wasm works on stable now!

wee_alloc/Cargo.toml, wee_alloc/src/lib.rs
std::hints::unreachable_unchecked is stable since 1.27.0
=> drop unreachable dependency

test.sh, test/src/lib.rs, wee_alloc/src/imp_static_array.rs, wee_alloc/src/lib.rs
Technically, at minimum we only assert that `imp::alloc_pages` returns a block of memory that is word-aligned, but it makes sense to me to keep it "page"-aligned as that is the granularity of allocation in the backend (this might be a system without virtual memory, so "page" is maybe a misnomer).
This should help with #85 
@ZackPierce or @DrGoldfire could you take a look at this?
+cc @nand-nor
=> Ensure that the static array backend's scratch heap is page-aligned
